import tkinter as tk 
import pandas
import matplotlib.pyplot as plt
import numpy as np
import GibbsInterfacialExcess, PosToCSV, ProxigramError, ProxigramPeakDecomp, ProxigramProfilePlot, ColumnModCheck, graph3d



def entryfilled():
    filepath = fileentry.get()
    modpath = modentry.get()
    newpath = newentry.get()

    print(filepath)
    print(modpath)
    print(newpath)

window = tk.Tk()
window.title("Proxigram Modification")

window.geometry('500x500')



label = tk.Label(window, text = "What is your original proxigram CSV filepath?").pack()
fileentry = tk.Entry(window)
fileentry.pack()

label = tk.Label(window, text = "What is the filepath of your modified proxigram CSV? \n (Generated by Manual Peak Decomposition)").pack()
modentry = tk.Entry(window)
modentry.pack()

label = tk.Label(window, text = "What is the filepath of the at% proxigram CSV \n from which you will plot a profile? (Generated by MPD)").pack()
newentry = tk.Entry(window)
newentry.pack()

btentryfill = tk.Button(window, text = "What's entered", command = entryfilled).pack()


def gibbsclicked():
    print("clicked")
    print("this is ur modpath: " + modpath)

    GibbsInterfacialExcess.getExcess()

def colmodcheckclicked():
    print("clicked")
    ColumnModCheck.colcheck()
    
def postocsvclicked():
    print("clicked")
    PosToCSV.csvbuild()
    
def graphclicked(): 
    print("clicked")
    graph3d.plotpoints()
    
def proxplotclicked():
    print("clicked")
    ProxigramProfilePlot.proxplot()
    
def proxerrorclicked():
    print("clicked")
    ProxigramError.proxerror()


def proxpeakdecompclicked():
    print("clicked")
    ProxigramPeakDecomp.entiredecomp()

btcolmod = tk.Button(window, text = "Column Mod Check", command = colmodcheckclicked).pack()
btgibbs = tk.Button(window, text = "Gibbsian Interfacial Excess", command = gibbsclicked).pack()
btgraph = tk.Button(window, text = "Graph POS CSV", command = graphclicked).pack()
btposcsv = tk.Button(window, text = "Create CSV from POS", command = postocsvclicked).pack()
btproxerror = tk.Button(window, text = "Generate Proxigram Error CSV", command = proxerrorclicked).pack()
btproxpeakdecomp = tk.Button(window, text = "Manual Proxigram Peak Decomposition", command = proxpeakdecompclicked).pack()
btproxprofplot = tk.Button(window, text = "Generate Proxigram Profile Plot", command = proxplotclicked).pack()





window.mainloop()
